function getRequiredElement(id) {
    const element = document.getElementById(id);

    if (!element) {
        throw new Error(`找不到必要元素 #${id}`);
    }

    return element;
}

export function getDomElements() {
    return {
        editorTabBtn: getRequiredElement("editorTabBtn"),
        aiTabBtn: getRequiredElement("aiTabBtn"),
        versionsTabBtn: getRequiredElement("versionsTabBtn"),
        editorTabPanel: getRequiredElement("editorTabPanel"),
        aiTabPanel: getRequiredElement("aiTabPanel"),
        versionsTabPanel: getRequiredElement("versionsTabPanel"),
        xmlInput: getRequiredElement("xmlInput"),
        sourceFormatSelect: getRequiredElement("sourceFormatSelect"),
        languageSelect: getRequiredElement("languageSelect"),
        urlInput: getRequiredElement("urlInput"),
        fetchBtn: getRequiredElement("fetchBtn"),
        dropzone: getRequiredElement("dropzone"),
        fileInput: getRequiredElement("fileInput"),
        uploadBtn: getRequiredElement("uploadBtn"),
        downloadXmlBtn: getRequiredElement("downloadXmlBtn"),
        downloadPngBtn: getRequiredElement("downloadPngBtn"),
        downloadPngFloatingBtn: getRequiredElement("downloadPngFloatingBtn"),
        openInDrawioBtn: getRequiredElement("openInDrawioBtn"),
        openDrawioLink: getRequiredElement("openDrawioLink"),
        currentFileNameInput: getRequiredElement("currentFileNameInput"),
        formatBtn: getRequiredElement("formatBtn"),
        clearXmlBtn: getRequiredElement("clearXmlBtn"),
        loadSampleBtn: getRequiredElement("loadSampleBtn"),
        viewerContainer: getRequiredElement("viewerContainer"),
        toast: getRequiredElement("toast"),
        loadingState: getRequiredElement("loadingState"),
        apiKeyInput: getRequiredElement("apiKeyInput"),
        modelInput: getRequiredElement("modelInput"),
        aiPrompt: getRequiredElement("aiPrompt"),
        currentSourceModeBadge: getRequiredElement("currentSourceModeBadge"),
        referenceDropzone: getRequiredElement("referenceDropzone"),
        referenceUploadBtn: getRequiredElement("referenceUploadBtn"),
        referenceFileInput: getRequiredElement("referenceFileInput"),
        clearReferenceFilesBtn: getRequiredElement("clearReferenceFilesBtn"),
        referenceFilesList: getRequiredElement("referenceFilesList"),
        selectedRegionEmpty: getRequiredElement("selectedRegionEmpty"),
        selectedRegionPreviewWrap: getRequiredElement("selectedRegionPreviewWrap"),
        selectedRegionPreview: getRequiredElement("selectedRegionPreview"),
        selectedRegionMeta: getRequiredElement("selectedRegionMeta"),
        clearSelectedRegionBtn: getRequiredElement("clearSelectedRegionBtn"),
        askAiBtn: getRequiredElement("askAiBtn"),
        askAiBtnText: getRequiredElement("askAiBtnText"),
        aiSpinner: getRequiredElement("aiSpinner"),
        drawioCompactPromptBtn: getRequiredElement("drawioCompactPromptBtn"),
        aiDemoBtn: getRequiredElement("aiDemoBtn"),
        convertMermaidBtn: getRequiredElement("convertMermaidBtn"),
        aiHistoryList: getRequiredElement("aiHistoryList"),
        aiHistoryEmpty: getRequiredElement("aiHistoryEmpty"),
        clearHistoryBtn: getRequiredElement("clearHistoryBtn"),
        openShortcutsBtn: getRequiredElement("openShortcutsBtn"),
        shortcutsModal: getRequiredElement("shortcutsModal"),
        shortcutsBackdrop: getRequiredElement("shortcutsBackdrop"),
        closeShortcutsBtn: getRequiredElement("closeShortcutsBtn"),
        geminiSettingsModal: getRequiredElement("geminiSettingsModal"),
        geminiSettingsBackdrop: getRequiredElement("geminiSettingsBackdrop"),
        openGeminiSettingsBtn: getRequiredElement("openGeminiSettingsBtn"),
        closeGeminiSettingsBtn: getRequiredElement("closeGeminiSettingsBtn"),
        cancelGeminiSettingsBtn: getRequiredElement("cancelGeminiSettingsBtn"),
        saveGeminiSettingsBtn: getRequiredElement("saveGeminiSettingsBtn"),
        highlightModeSelect: getRequiredElement("highlightModeSelect"),
        addHighlightBtn: getRequiredElement("addHighlightBtn"),
        eraseHighlightBtn: getRequiredElement("eraseHighlightBtn"),
        clearHighlightsBtn: getRequiredElement("clearHighlightsBtn"),
        selectionBox: getRequiredElement("selectionBox"),
        aiLoadingOverlay: getRequiredElement("aiLoadingOverlay"),
        pngExportLoadingOverlay: getRequiredElement("pngExportLoadingOverlay"),
        xmlExportLoadingOverlay: getRequiredElement("xmlExportLoadingOverlay")
    };
}
